<?php

namespace App\Http\Requests;

use App\Traits\ApiResponder;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Symfony\Component\HttpFoundation\Response;

class BaseRequest extends FormRequest
{
    use ApiResponder;

    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            //
        ];
    }

    public function failedValidation(Validator $validator)
    {
        if (request()->expectsJson()) {
            return $this->failed(
              __('validation.error.message'),
              Response::HTTP_UNPROCESSABLE_ENTITY,
              $validator->errors()->toArray()
            );
        }
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
